PrimeHoldingProject/PrimeHoldingProject/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrimeHoldingProject.Core.Contracts;
using PrimeHoldingProject.Core.Models.Employee;
using PrimeHoldingProject.Core.Models.User;
using PrimeHoldingProject.UserServices;
using System.Security.Claims;
using static PrimeHoldingProject.Infrastructure.Constants.RoleConstants;
using static PrimeHoldingProject.Core.Constants.MessageConstant;
using Microsoft.AspNetCore.Identity;
using PrimeHoldingProject.Infrastructure.Data.Models;

namespace PrimeHoldingProject.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUserService userService;
        private readonly IEmployeeService employeeService;
        private readonly SignInManager<ApplicationUser> signInManager;
        public EmployeeController(IUserService userService,
            IEmployeeService employeeService,
            SignInManager<ApplicationUser> signInManager)
        {
            this.userService = userService;
            this.employeeService = employeeService;
            this.signInManager = signInManager;
        }
        [HttpGet]
        public async Task<IActionResult> Become()
        {
            try
            {
                if (User.IsInRole(EmployeeConstant) || User.IsInRole(ManagerConstant))
                {
                    TempData[ErrorMessage] = "You are already an employee/manager!";
                    return RedirectToAction("Index", "Home");
                }
                var userId = GetUserId();
                var user = await userService.GetUserEmployeeInfoAsync(Guid.Parse(userId));
                return View(user);
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "An error occured!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Become(UserEmployeeViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Invalid info.");
                    return View();
                }
                var userId = GetUserId();
                await employeeService.BecomeEmployeeAsync(model, Guid.Parse(userId));
                TempData[SuccessMessage] = "You are an employee now! Please log in for changes to get saved.";
                await signInManager.SignOutAsync();
                return RedirectToAction("Login", "User");
            }
            catch (ArgumentException)
            {
                ModelState.AddModelError("", "Invalid user!");
                return View(model);
            }
        }
        [HttpGet]
        [Authorize(Roles = EmployeeConstant)]
        public async Task<IActionResult> Edit()
        {
            try
            {
                var userId = GetUserId();
                var user = await employeeService.GetEmployeeInformation(Guid.Parse(userId));
                return View(user);
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "An error occured!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserEmployeeViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Invalid info.");
                    return View();
                }
                var userId = GetUserId();
                await employeeService.EditEmployee(model, Guid.Parse(userId));
                TempData[SuccessMessage] = "You successfully updated your information!";
                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentNullException)
            {
                TempData[ErrorMessage] = "Invalid Employee.";
                return RedirectToAction("Index", "Home");

            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Invalid user.";
                return RedirectToAction("Index", "Home");

            }
        }
        [Authorize(Roles = EmployeeConstant)]
        public async Task<IActionResult> QuitJob()
        {
            try
            {
                await employeeService.QuitJobAsync(Guid.Parse(GetUserId()));
                await signInManager.SignOutAsync();
                TempData[SuccessMessage] = "You succesfully left work! Please log in to confirm changes!";
                return RedirectToAction("Login", "User");
            }
            catch (ArgumentNullException)
            {
                TempData[ErrorMessage] = "Invalid employee!";
                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Invalid user!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public async Task<IActionResult> MyTasks()
        {
            try
            {
                var tasks = await employeeService.MyTasksAsync(Guid.Parse(GetUserId()));
                return View(tasks);
            }
            catch (Exception)
            {
                TempData[ErrorMessage] = "Something went wrong!";
                return RedirectToAction("Index", "Home");
            }
        }
        private string GetUserId()
        {
            return User?.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;
        }
    }
}

PrimeHoldingProject/PrimeHoldingProject/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PrimeHoldingProject.Core.Contracts;
using PrimeHoldingProject.Core.Models.Task;
using PrimeHoldingProject.Core.Models.User;
using PrimeHoldingProject.Infrastructure.Data.Models;
using PrimeHoldingProject.UserServices;
using System.Security.Claims;
using static PrimeHoldingProject.Core.Constants.MessageConstant;
using static PrimeHoldingProject.Infrastructure.Constants.RoleConstants;

namespace PrimeHoldingProject.Controllers
{
    [Authorize]
    public class ManagerController : Controller
    {
        private readonly IUserService userService;
        private readonly IManagerService managerService;
        private readonly ITaskService taskService;
        private readonly IEmployeeService employeeService;
        private readonly SignInManager<ApplicationUser> signInManager;
        public ManagerController(IUserService userService,
            IManagerService managerService,
            ITaskService taskService,
            IEmployeeService employeeService,
            SignInManager<ApplicationUser> signInManager)
        {
            this.userService = userService;
            this.managerService = managerService;
            this.taskService = taskService;
            this.employeeService = employeeService;
            this.signInManager = signInManager;
        }
        [HttpGet]
        public async Task<IActionResult> Become()
        {
            try
            {
                if (User.IsInRole(ManagerConstant) || User.IsInRole(EmployeeConstant))
                {
                    TempData[ErrorMessage] = "You are already an employee/manager!";
                    return RedirectToAction("Index", "Home");
                }
                var userId = GetUserId();
                var model = await userService.GetUserManagerInfoAsync(Guid.Parse(userId));
                return View(model);
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Invalid user!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Become(UserManagerViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Invalid info.");
                    return View();
                }
                var userId = GetUserId();
                await managerService.BecomeManagerAsync(model, Guid.Parse(userId));
                TempData[SuccessMessage] = "You are now a manager! Please login to confirm changes!";
                await signInManager.SignOutAsync();
                return RedirectToAction("Login", "User");
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Something went wrong!";
                return RedirectToAction("Index", "Home");
            }

        }
        [HttpGet]
        [Authorize(Roles = ManagerConstant)]
        public async Task<IActionResult> Edit()
        {
            try
            {
                var userId = GetUserId();
                var user = await managerService.GetManagerInformation(Guid.Parse(userId));
                return View(user);
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "An error occured!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserManagerViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Invalid info.");
                    return View();
                }
                var userId = GetUserId();
                await managerService.EditManager(model, Guid.Parse(userId));
                TempData[SuccessMessage] = "You successfully updated your information!";
                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentNullException)
            {
                TempData[ErrorMessage] = "Invalid Employee.";
                return RedirectToAction("Index", "Home");

            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Invalid user.";
                return RedirectToAction("Index", "Home");

            }
        }
        [Authorize(Roles = ManagerConstant)]
        public async Task<IActionResult> QuitJob()
        {
            try
            {
                await managerService.QuitJobAsync(Guid.Parse(GetUserId()));
                await signInManager.SignOutAsync();
                TempData[SuccessMessage] = "You succesfully left work! Please log in to confirm changes!";
                return RedirectToAction("Login", "User");
            }
            catch (ArgumentNullException)
            {
                TempData[ErrorMessage] = "Invalid manager!";
                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Invalid user!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        [Authorize(Roles = ManagerConstant)]
        public async Task<IActionResult> AllEmployees()
        {
            var employees = await employeeService.AllEmployeesAsync();
            return View(employees);
        }
        [Authorize(Roles = ManagerConstant)]
        public async Task<IActionResult> FireEmployee(Guid employeeId)
        {
            try
            {
                await managerService.FireEmployeeAsync(employeeId);
                TempData[SuccessMessage] = "You successfully fired an employee!";
                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Something went wrong!";
                return RedirectToAction("Index", "Home");
            }
        }
        private string GetUserId()
        {
            return User?.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;
        }
    }
}

PrimeHoldingProject/PrimeHoldingProject/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrimeHoldingProject.Core.Contracts;
using PrimeHoldingProject.Core.Models.Task;
using System.Security.Claims;
using static PrimeHoldingProject.Core.Constants.MessageConstant;
using static PrimeHoldingProject.Infrastructure.Constants.RoleConstants;

namespace PrimeHoldingProject.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly ITaskService taskService;
        public TaskController(ITaskService taskService)
        {
            this.taskService = taskService;
        }
        [HttpGet]
        public async Task<IActionResult> All()
        {
            var tasks = await taskService.AllTasksAsync();
            return View(tasks);
        }
        [HttpGet]
        [Authorize(Roles = ManagerConstant)]
        public async Task<IActionResult> AllForManagers()
        {
            var tasks = await taskService.AllTasksForManagersAsync();
            return View(tasks);
        }
        public async Task<IActionResult> FinishTask(Guid taskId)
        {
            try
            {
                if (User.IsInRole(EmployeeConstant))
                {
                    await taskService.FinishTaskAsync(taskId, Guid.Parse(GetUserId()));
                    TempData[SuccessMessage] = "You successfully completed a task!";
                    return RedirectToAction(nameof(All));
                }
                TempData[ErrorMessage] = "You are not an employee!";
                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Something went wrong!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        [Authorize(Roles = ManagerConstant)]
        public IActionResult CreateTask()
        {
            return View(new CreateTaskViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> CreateTask(CreateTaskViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Invalid info.");
                    return View();
                }
                await taskService.CreateTaskAsync(model, Guid.Parse(GetUserId()));
                TempData[SuccessMessage] = "Successfully added a task!";
                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                TempData[ErrorMessage] = "An error occured!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        [Authorize(Roles = ManagerConstant)]
        public async Task<IActionResult> Edit(Guid taskId)
        {
            try
            {
                var task = await taskService.GetTaskForEditAsync(taskId);
                return View(task);
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Something went wrong!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TaskForEditViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Invalid info.");
                    return View();
                }
                await taskService.EditTaskAsync(model);
                TempData[SuccessMessage] = "You successfully edited the task!";
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentException)
            {
                TempData[ErrorMessage] = "Something went wrong!";
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize(Roles = ManagerConstant)]
        public async Task<IActionResult> Delete(Guid taskId)
        {
            try
            {
                await taskService.DeleteAsync(taskId);
                TempData[SuccessMessage] = "You successfully deleted the task!";
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentNullException)
            {
                TempData[ErrorMessage] = "You couldn't delete the task!";
                return RedirectToAction("Index", "Home");
            }
        }
        private string GetUserId()
        {
            return User?.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;
        }
    }
}

PrimeHoldingProject/PrimeHoldingProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using static PrimeHoldingProject.Infrastructure.Constants.RoleConstants;
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimeHoldingProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimeHoldingProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimeHoldingProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.IsInRole(EmployeeConstant) || User.IsInRole(ManagerConstant))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="All">All Tasks</a>
                            </li>
                        }
                        @if (!User.IsInRole(EmployeeConstant) && !User.IsInRole(ManagerConstant))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Become">Become an employee</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Become">Become a manager</a>
                            </li>
                        }
                        @if (User.IsInRole(EmployeeConstant))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="MyTasks">My Tasks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Edit">Edit my information</a>
                            </li>
                        }
                        @if (User.IsInRole(ManagerConstant))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="AllEmployees">All Employees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Edit">Edit my information</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="CreateTask">Create Task</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-blue" asp-area="" asp-controller="Task" asp-action="AllForManagers" style="color: blue">All tasks for managers</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PrimeHoldingProject </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PrimeHoldingProject/PrimeHoldingProject/Views/Shared/_UserMessages.cshtml
@using PrimeHoldingProject.Core.Constants

@if (TempData[MessageConstant.ErrorMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[MessageConstant.ErrorMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.WarningMessage] != null)
{
    <script>
        $(function () { toastr.warning('@TempData[MessageConstant.WarningMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.SuccessMessage] != null)
{
    <script>
        $(function () { toastr.success('@TempData[MessageConstant.SuccessMessage].ToString()'); });
    </script>
}